language: php
sudo: false

php:
  - 7.3

env:
  - TRAVIS_NODE_VERSION="10"
  - TRAVIS_NODE_VERSION="14"

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - composer self-update
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION

install:
  - node -v
  - npm install
  - composer validate
  - composer install -o --prefer-dist --no-interaction

script:
  - npm run development
  - npm run production
