#!/usr/bin/env php
<?php

use Symfony\Component\Console\Exception\RuntimeException;

if (file_exists($composer = __DIR__ . '/vendor/autoload.php')) {
    require $composer;

    new Tonik\Gin\Foundation\Console\CLI();

    return;
}

throw new RuntimeException("Please, install composer dependences before running CLI.");
