#!/usr/bin/env php
<?php

if (file_exists($composer = __DIR__ . '/vendor/autoload.php')) {
    require $composer;
}

$app = new Symfony\Component\Console\Application('Tonik&Gin CLI');

$app->add(new Tonik\Gin\Foundation\Console\InitCommand);

$app->run();