#!/usr/bin/env php
<?php

use Symfony\Component\Console\Exception\RuntimeException;

if (file_exists($composer = __DIR__ . '/vendor/autoload.php')) {
    require $composer;

    return new Tonik\Gin\Foundation\Console\CLI(__DIR__);
}

throw new RuntimeException("Please, install composer dependences before running CLI.");
